name: GledhillRules
favicon: null
layout_spectrum: 0.23511255835182965
typography_spectrum: 0.30807387945242226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.24032024503685534
  lightness: 0.2827527273911983
  saturation: 0.6730019296519458
  rhythmicContrast: 0.6048563504591584
purpose: []
